# scene
scene: building
model_id: Allensville # target model name
model_type: '' # ''|_seg
is_interactive: false
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_resolution: 0.1
trav_map_erosion: 3
num_waypoints: 10
gravity: 0 # set to zero to make sure position and orientation are correct

# robot
robot: Turtlebot
is_discrete: false
velocity: 1.0

# task, observation and action
task: pointgoal
target_dist_min: 1.0
target_dist_max: 10.0
initial_pos_z_offset: 0.1
additional_states_dim: 4

# reward
reward_type: geodesic
success_reward: 10.0
slack_reward: -0.01
potential_reward_weight: 1.0
collision_reward_weight: -0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36
max_step: 500
max_collisions_allowed: 500
goal_format: polar

# sensor spec
output: [sensor, rgb, depth, scan]
# image
fisheye: false
panorama: true # render panorama
image_width: 512 # for panorama rendering, width and height must be the same
image_height: 512
vertical_fov: 90 # 90 fov for panorama rendering
# depth
depth_low: 0.8
depth_high: 3.5
# scan
n_horizontal_rays: 228
n_vertical_beams: 1
laser_linear_range: 5.6
laser_angular_range: 240.0
min_laser_dist: 0.05
laser_link_name: scan_link

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: false

